### ISSUE TITLE
Not sure I understand how to implement this...?

### ISSUE THREAD

**Issue by jfrux** [chrisfarber/ember-flexure#1]
I read the README and it talks about the Resolver... but not sure what that means really?
Forgive me, I'm new to Ember!

**Comment by chrisfarber** [comment]
Ah, sorry.

You are almost certainly using the new resolver already. I wouldn't worry about it – it's a historical concern.

I should warn you that this project has languished for a while. I still think the idea behind it is worthwhile, and that it occupies a useful space in relation to other frameworks for Ember, however it's desperately in need of some tests, updating, and refactoring.

If I were you, I would choose something else for now… or accept that you'll need to put some work into flexure as you go.
